matrix:
  include:
    - language: rust
      rust: 
        - stable
        - beta
        - nightly
      before_script:
        - cargo build --release --verbose
    - language: node_js
      node_js:
        - "8"
      script:
        - node index.js
  allow_failures:
    - rust: nightly